#define CF_MODULE_LAYOUT_BINDING
#define CF_MODULE_CONFIG
//#define CF_MODULE_PERMISSIONS

#define CF_GHOSTICONS

#define CF_DebugUI

#ifdef CF_MODULE_LAYOUT_BINDING
#define CF_MODEL_VIEW_BINDING
#endif
