set WorkDrive=P:\
set ModBuildDirectory=P:\Mods\
set KeyDirectory=P:\Keys\
set KeyName=JacobMango
set GameDirectory=C:\Games\steamapps\common\DayZ\
set ServerDirectory=C:\Games\steamapps\common\DayZServer\
set WorkbenchDirectory=C:\Games\steamapps\common\DayZ Tools\Bin\Workbench\
set ModName=@Community-Framework
set ServerPassword=
set ServerProfileDirectory=ServerProfile
set Port=2302
set PrefixLinkRoot=JM\CF
set ClientEXE=DayZDiag_x64.exe
set ServerEXE=DayZDiag_x64.exe
set WorkbenchEXE=workbenchApp.exe
set ServerLaunchParams=-server -filePatching
set ClientLaunchParams=-filePatching
set WorkbenchLaunchParams=-filePatching
set ScriptsPrefix=JM\CF\Scripts
set GUIPrefix=JM\CF\GUI
set MajorVersion=1
set MinorVersion=1
set VersionFileLocation=JM\CF\Scripts\Data\Version.hpp
