set WorkDrive=P:\
set ModBuildDirectory=H:\DayZModding\Mods\
set KeyName=Jacob_Mango_V3
set KeyDirectory=H:\DayZModding\Keys\
set GameDirectory=C:\Program Files (x86)\Steam\steamapps\common\DayZ\
set ServerDirectory=C:\Program Files (x86)\Steam\steamapps\common\DayZServer\
set WorkbenchDirectory=C:\Program Files (x86)\Steam\steamapps\common\DayZ Tools\Bin\Workbench\
set ServerPassword=
set AdditionalMPMods=@Community-Online-Tools
set AdditionalSPMods=@Community-Online-Tools
set SPMission=.\Missions\dayzOffline.ChernarusPlus
set MPMission=.\MPMissions\dayzOffline.ChernarusPlus
set ServerProfileDirectory=ServerProfile
set Port=2302
set ClientEXE=DayZDiag_x64.exe 
set ServerEXE=DayZServer_x64.exe
set WorkbenchEXE=workbenchApp.exe
set ServerLaunchParams=-server -filePatching
set ClientLaunchParams=
set PlayerName=Jaocv
set ServerConfig=serverDz.cfg
